### ISSUE TITLE
It must have a basic playback functionalities

### ISSUE THREAD

**Issue by SopMar** [m-cakir/radio-player#1]
Nice implementation.

It must have a basic playback functionalities -

(1) It should work like a Playlist 
1.1. If first song is over, then it should start second automatically and so on
1.2. Keep controls at bottom (to move next and previous) where you using play/pause

**Comment by m-cakir** [comment]
It's just example of radio station streaming. Only you can change current playing the channel.

If you wanna play songs (mp3, mp4 etc.) with full features (prev, next, shuffle etc.), you can see [this](https://github.com/naman14/Timber) project.
