### ISSUE TITLE
Upgrade ExoPlayer and parse external JSON

### ISSUE THREAD

**Issue by JDVU** [m-cakir/radio-player#2]
Helllo
Could you help me upgrade ExoPlayer for support HLS and parse external JSON by url?
Thanks.

**Comment by m-cakir** [comment]
You can see HLS streaming code block, you need to change media source type.

`MediaSource mediaSource = new HlsMediaSource(Uri.parse(HLS_URL), dataSourceFactory, handler, null);
exoPlayer.prepare(mediaSource);`

If you wanna parse JSON by url, you need to save and parse it. You can make it easily with Retrofit, Volley or some other networking libraries.
