### ISSUE TITLE
player lack newest stable Exoplayer support

### ISSUE THREAD

**Issue by JanuszChmiel** [m-cakir/radio-player#8]
Good afternoon,
You have created very stable and efficient player. I deeply appreciate yours programmers knowledge, since you have created Java service, which enable us to use ExoPlayer as A service, this allow users to play live Internet radios even if Android device screen have been turned off. And player even work on Android 4.1.2 API 16. But I Am wondering, how complex would be to reconstruct yours player Java code so also newest stable Exoplayer library would be used. Currently, I Am getting Java bugs related to overide that some part of yours code can not be overided if I use newer Exoplayer release than The older version, which you have used. Or newest Exoplayer prevent its developers to use it as A Android service so live streams can not be play on background when Android device display have been turned off? But really, you have completed outstanding development work and thank you for .Json Android user interface support, since I could modify yours player to listen my favourite Czech radio stations. And yours code is very easy to understand even by visually impaired advanced users or developers. The amazing is, that I can use Gradlew command to build my debug .apk with no need to use Android studio. Very well done.

**Comment by m-cakir** [comment]
repo updated for exoplayer 2.8.2 (currently newest version)
